version: "3.7"

services:
    database:
        image: neo4j:4.0
        environment:
            NEO4J_dbms_default__database: article
        env_file:
         - .env
        volumes:
         - database:/data
        networks:
            blog:
                aliases:
                 - database
        ports:
            - "7474:7474"

    backend:
        image: docker.pkg.github.com/evian-zhang/evian-blog/blog_backend:latest
        environment: 
            CONFIG_FILE: /app/backend_config
            DATABASE_PASSWORD_FILE: /run/secrets/database_password
        configs:
         - source: backend_config
           target: /app/backend_config
        secrets:
         - database_password
        networks:
            blog:
                aliases:
                    - backend
        ports:
            - "8080:8080"
        volumes:
            - resume:/app/resume
    
    frontend:
        image: docker.pkg.github.com/evian-zhang/evian-blog/blog_frontend:latest
        environment:
            CONFIG_FILE: /frontend_config
        configs:
         - frontend_config
        networks:
            blog:
                aliases:
                    - frontend
        ports:
            - "8081:8081"

networks:
    blog:
        driver: overlay
        attachable: true

volumes:
    database:
    resume:

configs:
    backend_config:
        file: ./backend_config.toml
    frontend_config:
        file: ./frontend_config.json

secrets:
    database_password:
        external: true
        name: blog_database_password
    