version: "3.8"

services:
    database:
        image: neo4j:4.0
        environment:
            NEO4J_AUTH: ${NEO4J_AUTH}
            NEO4J_dbms_default__database: blog
        secrets:
         - neo4j_auth
        volumes:
         - database:/data
        networks:
            blog:
                aliases:
                 - database
        ports:
            - "8080:8080"

    backend:
        image: docker.pkg.github.com/evian-zhang/evian-blog/blog_backend:latest
        environment: 
            CONFIG_FILE: /app/backend_config
            DATABASE_PASSWORD_FILE: /run/secrets/database_password
        configs:
         - source: backend_config
           target: /app/backend_config
        secrets:
         - database_password
        networks:
            blog:
                aliases: 
                    - backend
        ports:
            - "8080:8080"
    
    frontend:
        image: docker.pkg.github.com/evian-zhang/evian-blog/blog_frontend:latest
        environment:
            CONFIG_FILE: /app/frontend_config
        configs:
         - source: frontend_config
           target: /app/frontend_config
        networks:
            blog:

networks:
    blog:
        driver: overlay
        attachable: true

volumes:
    database:
    img:

configs:
    backend_config:
        external: true
        name: blog_backend_config
    frontend_config:
        external: true
        name: blog_frontend_config

secrets:
    database_password:
        external: true
        name: blog_database_password
    