version: "3.7"

services:
    database:
        image: neo4j:4.0
        environment:
            NEO4J_dbms_default__database: blog
        env_file:
         - .env
        volumes:
         - database:/data
        networks:
            blog:
                aliases:
                 - database
        ports:
            - "7474:7474"

    backend:
        image: docker.pkg.github.com/evian-zhang/evian-blog/blog_backend:latest
        environment: 
            CONFIG_FILE: /app/backend_config
            DATABASE_PASSWORD_FILE: /run/secrets/database_password
        configs:
         - source: backend_config
           target: /app/backend_config
        secrets:
         - database_password
        networks:
            blog:
                aliases:
                    - backend
        ports:
            - "8080:8080"
    
    frontend:
        image: evianzhang1999/blog_frontend:1.0
        environment:
            CONFIG_FILE: /frontend_config
        configs:
         - frontend_config
        networks:
            blog:

    nginx:
        image: nginx:1.17-alpine
        configs:
         - source: nginx_config
           target: /etc/nginx/nginx.conf
        networks:
            blog:
        volumes:
         - img:/img
        ports:
            - "80:80"

networks:
    blog:
        driver: overlay
        attachable: true

volumes:
    database:
    img:

configs:
    backend_config:
        external: true
        name: blog_backend_config
    nginx_config:
        external: true
        name: blog_nginx_config
    frontend_config:
        external: true
        name: blog_frontend_config

secrets:
    database_password:
        external: true
        name: blog_database_password
    