package top.evian_zhang.evianblog.utils.articlelistview

import android.content.Context
import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.TextView
import androidx.fragment.app.activityViewModels
import androidx.lifecycle.Observer
import androidx.navigation.fragment.findNavController
import androidx.navigation.fragment.navArgs
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView

import top.evian_zhang.evianblog.R
import top.evian_zhang.evianblog.api.ArticleMetasFetcher
import top.evian_zhang.evianblog.api.BlogAPI
import top.evian_zhang.evianblog.views.writings.WritingsViewModel
import top.evian_zhang.evianblog.views.writings.tag.TagDetailsFragmentDirections

class ArticleListFragment : Fragment() {
    // If viewModel is null, then this fragment is served as ArticleTotalView, and is generated by navigation
    // If viewModel is not null, then this fragment is served as xxxDetailView, and is generated by viewPager's adapter
    private var viewModel: ArticleListViewModel? = null

    fun setViewModel(viewModel: ArticleListViewModel) {
        this.viewModel = viewModel
    }

    private val onArticleTitlePressed = { title: String ->
        val viewModel: WritingsViewModel by activityViewModels()
        viewModel.toSubview(WritingsViewModel.WritingsSubview.Article)
        val navController = this.findNavController()
        navController.navigate(ArticleListFragmentDirections.actionArticleListFragmentToArticleDetailsFragment(title))
    }
    private val onTagNamePressed = { name: String ->
        val viewModel: WritingsViewModel by activityViewModels()
        viewModel.toSubview(WritingsViewModel.WritingsSubview.Tag)
        val navController = this.findNavController()
        navController.navigate(ArticleListFragmentDirections.actionArticleListFragmentToTagDetailsFragment(name))
    }
    private val onSeriesNamePressed = { name: String ->
        val viewModel: WritingsViewModel by activityViewModels()
        viewModel.toSubview(WritingsViewModel.WritingsSubview.Series)

    }

    private val adapter = ArticleMetaAdapter(this.onArticleTitlePressed, onTagNamePressed, onSeriesNamePressed)

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
    }

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_article_list, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        val viewModel = this.viewModel ?: {
            val args: ArticleListFragmentArgs by navArgs()

            val activityViewModel: ArticleListViewModel by activityViewModels {
                ArticleListViewModelFactory(args.fetcherType, args.key, BlogAPI())
            }

            activityViewModel
        }()
        viewModel.getArticles().observe(viewLifecycleOwner, Observer { pagedArticleMetaList ->
            this.adapter.submitList(pagedArticleMetaList)
        })

        val writingsViewModel: WritingsViewModel by activityViewModels()
        writingsViewModel.getCurrentSubview().observe(viewLifecycleOwner, Observer { subview ->
            if (!writingsViewModel.programmatically) {
                val navController = this.findNavController()
                when (subview) {
                    WritingsViewModel.WritingsSubview.Article -> {
                        when (viewModel.fetcherType) {
                            ArticleMetasFetcher.TagsDetail -> {
                                navController.navigate(TagDetailsFragmentDirections.actionTagDetailsFragmentToArticleListFragment())
                            }
                            ArticleMetasFetcher.SeriesDetail -> {

                            }
                        }
                    }
                    WritingsViewModel.WritingsSubview.Tag -> {
                        if (viewModel.fetcherType == ArticleMetasFetcher.ArticleTotal || viewModel.fetcherType == ArticleMetasFetcher.SeriesDetail) {
                            navController.navigate(ArticleListFragmentDirections.actionArticleListFragmentToTagTotalFragment())
                        }
                    }
                    WritingsViewModel.WritingsSubview.Series -> {

                    }
                }
            }
        })

        val recyclerView = view.findViewById<RecyclerView>(R.id.article_list)
        recyclerView.adapter = this.adapter
        // see https://stackoverflow.com/a/35802948/10005095
        recyclerView.layoutManager = LinearLayoutManager(activity)

        val keyView: TextView = view.findViewById(R.id.article_list_key)
        if (viewModel.fetcherType == ArticleMetasFetcher.ArticleTotal) {
            keyView.visibility = View.GONE
        } else {
            keyView.text = viewModel.key
            keyView.visibility = View.VISIBLE
        }
    }
}