name: Backend-CI

on:
    push:
        branches:
            - master
        paths:
            - 'backend/**'

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            working-directory: ./backend

        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: cargo build --verbose
              working-directory: ${{ env.working-directory }}
            - name: Run tests
              run: cargo test --verbose
              working-directory: ${{ env.working-directory }}
