name: Backend-Deploy

on:
    push:
        tags:
        - 'backend@v*'

env:
    IMAGE_NAME: blog_backend

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            working-directory: ./backend

        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: docker build .
              working-directory: ${{ env.working-directory }}

    push:
        needs: test

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Build image
              run: docker build . --tag $IMAGE_NAME
              working-directory: ${{ env.working-directory }}
            - name: Log into Docker Hub
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }}
            - name: Push image
              run: |
                IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

                IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

                VERSION=$(echo "${{ github.ref }}") | sed -e 'e,.*/\(.*\),\1,')

                [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^backend@v//')

                echo IMAGE_ID=$IMAGE_ID
                echo VERSION=$VERSION

                docker tag image $IMAGE_ID:$VERSION
                docker tag image $IMAGE_ID:latest
                docker push $IMAGE_ID:$VERSION
                docker push $IMAGE_ID:latest
        